name: Python Lint and Security

on:
  push:
    branches: [ "main" ]

jobs:
  check_with_black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents pushing directly to protected branches

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "."
          src: './src/'

  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: |
          cd src/
          python -m ruff check .
          python -m ruff format --check .